#!/bin/sh

########## Build kernel ##############


cd mini-linux/src

git clone --depth 1 https://github.com/torvalds/linux.git

cd linux

make menuconfig
# IPV6_SIT=n

make -j 4 

cd ../..

ls -lh

