#!/bin/sh

########## Create basic syslinux.cfg ##########

cd mini-linux


### syslinux.cfg: ###

cat <<EOF > boot-partition/syslinux.cfg
DEFAULT /bzImage -initrd=/init.cpio 
EOF


### init: ###

cat <<EOF > initramfs/init
#!/bin/sh

/bin/sh
EOF

chmod +x initramfs/init

cd ..
