#!/bin/sh

########## Create basic syslinux.cfg ##########

cd mini-linux


### syslinux.cfg: ###

mkdir -p boot-prepare

cat <<EOF > boot-prepare/syslinux.cfg
DEFAULT /bzImage -initrd=/init.cpio 
EOF


### init: ###

mkdir -p initramfs

cat <<EOF > initramfs/init
#!/bin/sh

/bin/sh
EOF

chmod +x initramfs/init

cd ..
