#!/bin/sh

########## Busybox ##########


cd mini-linux/src

git clone --depth 1 https://git.busybox.net/busybox
 
cd busybox

make menuconfig
# Settings --> 
#    [*] Build static binary (no shared libs)
### Bug TC (Traffic Control):
# Networking Utilities  --->
#    [ ] tc (Traffic Control)


make -j 8

cd ../..

