#!/bin/sh

########## Build kernel ##############


mkdir -p mini-linux/src

cd mini-linux/src

git clone --depth 1 https://github.com/torvalds/linux.git

cd linux

make menuconfig
# IPV6_SIT=n

make -j 4 

cp arch/x86/boot/bzImage ../../

cd ../..

ls -lh

