#!/bin/sh

########## Busybox ##########


cd src

git clone --depth 1 https://git.busybox.net/busybox
 
cd busybox

make menuconfig
# Settings > [*] Build static binary (no shared libs)
# CONFIG_STATIC=y

make -j 8


make CONFIG_PREFIX=../../initramfs install

cd ../../initramfs

ls -lh

rm linuxrc

cd ..

