#!/bin/sh

########## Boot from disk ##########

cd mini-linux

mkdir -p boot-mount

umount boot-mount

rm boot.fat

dd if=/dev/zero of=boot.fat bs=1M count=20

mkfs -t fat boot.fat

syslinux boot.fat

mount -t vfat boot.fat boot-mount

cat <<EOF > syslinux.cfg
DEFAULT /bzImage -initrd=/init.cpio 
EOF

cp bzImage init.cpio syslinux.cfg boot-mount/

umount boot-mount



