#!/bin/sh

########## Finish build ##########

cd mini-linux


# kernel copy:

cp src/linux/arch/x86/boot/bzImage boot-partition/


# busybox install:

cd src/busybox

make CONFIG_STATIC=y CONFIG_PREFIX=../../initramfs install

cd ../../initramfs

ls -lh

rm linuxrc


# initramfs:

find . | cpio -o -H newc > ../boot-partition/init.cpio


# boot partition

cd ..

mkdir -p boot-mount-tmp

rm boot.fat

prepsize=$(du boot-partition | cut -f 1 | tail -1)
initsize=$(du initramfs | cut -f 1 | tail -1)
bootsize=$(echo "(($prepsize + $initsize) / 1000) + 1" | bc)

dd if=/dev/zero of=boot.fat bs=1M count=$bootsize

mkfs -t fat boot.fat

syslinux boot.fat

mount -t vfat boot.fat boot-mount-tmp

cp boot-partition/* boot-mount-tmp/

umount boot-mount-tmp

rmdir boot-mount-tmp

ls -lh




