#!/bin/sh

########## Finish build ##########

cd mini-linux/initramfs

find . | cpio -o -H newc > ../init.cpio

cd ..

mkdir -p boot-mount

umount boot-mount

rm boot.fat

dd if=/dev/zero of=boot.fat bs=1M count=20

mkfs -t fat boot.fat

syslinux boot.fat

mount -t vfat boot.fat boot-mount

cp bzImage init.cpio syslinux.cfg boot-mount/

umount boot-mount

ls -lh




