#!/bin/sh

cd initramfs

find . | cpio -o -H newc > ../init.cpio

cd ..

dd if=/dev/zero of=boot.fat bs=1M count=20

mkfs -t fat boot.fat

syslinux boot.fat

mount -t vfat boot.fat boot-mount

cp bzImage init.cpio boot-mount/

cat <<EOF > boot-mount/syslinux.cfg
DEFAULT /bzImage -initrd=/init.cpio 
EOF

umount boot-mount