#!/bin/sh

cd mini-linux/initramfs

find . | cpio -o -H newc > ../init.cpio

cd ..

dd if=/dev/zero of=boot.fat bs=1M count=20

mkfs -t fat boot.fat

syslinux boot.fat

mount -t vfat boot.fat boot-mount

ls -l 

cp syslinux.cfg bzImage init.cpio boot-mount/

umount boot-mount