#!/bin/bash

apt update

apt install -y bc bison bzip2 cpio curl flex gcc git make vim libelf-dev libncurses-dev libssl-dev syslinux isolinux genisoimage dosfstools grub-common xorriso grub-pc-bin grub-common qemu-system-x86 xz-utils

mkdir -p mini-linux/boot-partition
mkdir -p mini-linux/initramfs
mkdir -p mini-linux/src

cd mini-linux

enable_config() {
    local option="$1"
    sed -i "s/# $option is not set/$option=y/g" .config
}

disable_config() {
    local option="$1"
    sed -i "s/$option=y/# $option is not set/g" .config
}

#####################################################
## Compilação Kernel Linux
#####################################################

cd src
git clone --depth 1 https://github.com/torvalds/linux.git
cd linux

make defconfig

enable_config "CONFIG_BLK_DEV_INITRD"
enable_config "CONFIG_DEVTMPFS"
enable_config "CONFIG_DEVTMPFS_MOUNT"
enable_config "CONFIG_TMPFS"
enable_config "CONFIG_PROC_FS"
enable_config "CONFIG_SYSFS"
enable_config "CONFIG_TTY"
enable_config "CONFIG_VT"
enable_config "CONFIG_VT_CONSOLE"
enable_config "CONFIG_DEVPTS"
enable_config "CONFIG_DEVPTS_MULTIPLE_INSTANCES"
enable_config "CONFIG_UNIX98_PTYS"
enable_config "CONFIG_SERIAL_8250"
enable_config "CONFIG_SERIAL_8250_CONSOLE"


## suporte a cd-rom (opcional):
for opt in \
    CONFIG_BLK_DEV_SR \
    CONFIG_BLK_DEV_SR_VENDOR \
    CONFIG_CHR_DEV_SG \
    CONFIG_ATA \
    CONFIG_ATA_PIIX \
    CONFIG_SATA_AHCI \
    CONFIG_ISO9660_FS
do
    enable_config "$opt"
done
### fim suporte a cd-rom


make -j$(nproc)

cp arch/x86/boot/bzImage ../../boot-partition/

cd ../..

#####################################################
## Compilação Busybox
#####################################################

cd src

git clone --depth 1 https://git.busybox.net/busybox

cd busybox

make defconfig
enable_config "CONFIG_STATIC"
disable_config "CONFIG_TC"

make -j$(nproc)

make CONFIG_STATIC=y CONFIG_PREFIX=../../initramfs install

cd ../..


#####################################################
### initramfs
#####################################################

cd initramfs

cat <<'EOF' > init
#!/bin/sh

exec 0</dev/console 1>/dev/console 2>/dev/console

echo "[INIT] Montando pseudo-sistemas..."

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts none /dev/pts

echo "[INIT] Iniciando busca por init.sh..."

mkdir -p /mnt
FOUND=""

# Lista todos os block devices (exceto ram, loop, dm)
BLOCKS=$(ls /dev | grep -E '^(sd|vd|hd|sr)[a-z][0-9]?$|^sr[0-9]$')

wait_for_block() {
    DEV="$1"

    echo "[INIT] Aguardando $DEV ficar pronto..."

    for i in $(seq 1 20); do
        # dispositivo existe fisicamente?
        if [ -b "$DEV" ]; then
            # tem tamanho válido?
            SIZE=$(cat /sys/block/$(basename $DEV)/size 2>/dev/null || echo 0)
            if [ "$SIZE" -gt 0 ]; then                
                echo "[INIT] $DEV pronto! (size=$SIZE)"
                return 0
            fi
        fi
        sleep 0.2
    done

    echo "[INIT] Timeout esperando $DEV"
    return 1
}


for dev in $BLOCKS; do
    DEVNODE="/dev/$dev"

    if echo "$dev" | grep -qE '^sr[0-9]$'; then
        # espera sr0 ficar pronto
        wait_for_block "/dev/$dev"
    fi

    # Se for disco (sda), cria partição padrão (sda1)
    if echo "$dev" | grep -qE '^(sd|vd|hd|sr)[a-z]$'; then
        DEVNODE="/dev/${dev}1"
    fi

    if [ -b "$DEVNODE" ]; then
        echo "[INIT] Tentando montar $DEVNODE..."

        mount -t auto "$DEVNODE" /mnt 2>/dev/null
        if [ $? -eq 0 ]; then
            if [ -f /mnt/init.sh ]; then
                echo "[INIT] init.sh encontrado em $DEVNODE! Executando..."
                chmod +x /mnt/init.sh
                setsid /mnt/init.sh
                FOUND="yes"
                break
            fi            
        fi
    fi
done

echo "[INIT] Execução de init.sh finalizada. Abrindo shell."
exec /bin/sh
EOF

chmod +x init

ls -lh

rm linuxrc

mkdir -p {bin,sbin,etc,proc,sys,usr/bin,usr/sbin,dev,tmp,var,mnt}

cd dev

mknod -m 622 console c 5 1
mknod -m 666 null c 1 3

cd ../..

#####################################################
### Networking
#####################################################

cd initramfs

mkdir -p usr/sbin/

cat <<EOF > usr/sbin/start-networking
#!/bin/sh

cd /sys/class/net/

for i in *
do 
  ip link set \$i up
done

udhcpc -n 2>&1 > /dev/null
exit 0

EOF

chmod +x usr/sbin/start-networking

mkdir -p usr/share/udhcpc/

curl https://raw.githubusercontent.com/mschlenker/TinyCrossLinux/refs/heads/master/patches/usr-share-udhcpc-default.script -o usr/share/udhcpc/default.script

chmod +x usr/share/udhcpc/default.script

cd ..



#####################################################
### Partclone 
#####################################################

apt-get install -y \
  build-essential \
  autoconf automake libtool pkg-config \
  uuid-dev zlib1g-dev libncurses5-dev \
  libssl-dev e2fslibs-dev gettext autopoint libxxhash-dev xsltproc
cd src
git clone --depth 1 https://github.com/Thomas-Tsai/partclone.git

./autogen
./configure \
  --disable-man \
  --enable-extfs \
  --enable-ntfs \
  --enable-fat \
  --enable-exfat \
  --enable-static \
  --disable-shared \
  --disable-nls \
  CFLAGS="-O2" \
  LDFLAGS="-static" 

make install DESTDIR=$(pwd)/../../initramfs
rm -rf ../../initramfs/usr/local/share/man
cd ../..


#####################################################
### Build initramfs and run
#####################################################

cd initramfs

find . -print0 | cpio --null -ov --format=newc | gzip -9 > ../boot-partition/initramfs.cpio.gz

cd ..

qemu-system-x86_64 -kernel boot-partition/bzImage -initrd boot-partition/initramfs.cpio.gz -append "loglevel=8"

#####################################################
### Build basic ISO and run
#####################################################


cd src/linux
make isoimage FDINITRD=../../boot-partition/initramfs.cpio.gz FDARGS="initrd=/initramfs.cpio.gz"

cd ../..

mv src/linux/arch/x86/boot/image.iso mini-linux-basic.iso

qemu-system-x86_64 -cdrom mini-linux-basic.iso -m 512



#####################################################
### Build ISO/Grub and run 
#####################################################

cd boot-partition

cat <<EOF > init.sh
#!/bin/sh
echo "[INITCDROM] init.sh do CD-ROM foi executado."
EOF

chmod +x init.sh

mkdir -p boot/grub

cat > boot/grub/grub.cfg << EOF
set timeout=5
set default=0

menuentry "Mini Linux" {
    linux /bzImage loglevel=8
    initrd /initramfs.cpio.gz
}
EOF

cd ..

grub-mkrescue --verbose -o mini-linux.iso boot-partition/



qemu-system-x86_64 -cdrom mini-linux.iso -m 512






