#!/bin/bash

apt update

apt install -y bc bison bzip2 cpio flex gcc git make vim libelf-dev libncurses-dev libssl-dev syslinux isolinux genisoimage dosfstools grub-common xorriso qemu-system-x86 xz-utils

mkdir -p mini-linux/boot-partition
mkdir -p mini-linux/initramfs
mkdir -p mini-linux/src

cd mini-linux

enable_config() {
    local option="$1"
    sed -i "s/# $option is not set/$option=y/g" .config
}

disable_config() {
    local option="$1"
    sed -i "s/$option=y/# $option is not set/g" .config
}

#####################################################
## Compilação Kernel Linux
#####################################################

cd src
git clone --depth 1 https://github.com/torvalds/linux.git
cd linux

make defconfig


## suporte a cd-rom (opcional):
for opt in \
    CONFIG_BLK_DEV_SR \
    CONFIG_BLK_DEV_SR_VENDOR \
    CONFIG_CHR_DEV_SG \
    CONFIG_ATA \
    CONFIG_ATA_PIIX \
    CONFIG_SATA_AHCI \
    CONFIG_ISO9660_FS
do
    enable_config "$opt"
done
### fim suporte a cd-rom


make -j$(nproc)

cp arch/x86/boot/bzImage ../../boot-partition/

cd ../..

#####################################################
## Compilação Busybox
#####################################################

cd src

git clone --depth 1 https://git.busybox.net/busybox

cd busybox

make defconfig
enable_config "CONFIG_STATIC"
disable_config "CONFIG_TC"

make -j$(nproc)

make CONFIG_STATIC=y CONFIG_PREFIX=../../initramfs install

cd ../..


#####################################################
### initramfs
#####################################################

cd initramfs

cat <<'EOF' > init
#!/bin/sh

exec 0</dev/console 1>/dev/console 2>/dev/console

echo "[INIT] Montando pseudo-sistemas..."

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev

echo "[INIT] Iniciando busca por init.sh..."

mkdir -p /mnt
FOUND=""

# Lista todos os block devices (exceto ram, loop, dm)
BLOCKS=$(ls /dev | grep -E '^(sd|vd|hd|sr)[a-z][0-9]?$|^sr[0-9]$')

wait_for_block() {
    DEV="$1"

    echo "[INIT] Aguardando $DEV ficar pronto..."

    for i in $(seq 1 20); do
        # dispositivo existe fisicamente?
        if [ -b "$DEV" ]; then
            # tem tamanho válido?
            SIZE=$(cat /sys/block/$(basename $DEV)/size 2>/dev/null || echo 0)
            if [ "$SIZE" -gt 0 ]; then                
                echo "[INIT] $DEV pronto! (size=$SIZE)"
                return 0
            fi
        fi
        sleep 0.2
    done

    echo "[INIT] Timeout esperando $DEV"
    return 1
}


for dev in $BLOCKS; do
    DEVNODE="/dev/$dev"

    if echo "$dev" | grep -qE '^sr[0-9]$'; then
        # espera sr0 ficar pronto
        wait_for_block "/dev/$dev"
    fi

    # Se for disco (sda), cria partição padrão (sda1)
    if echo "$dev" | grep -qE '^(sd|vd|hd|sr)[a-z]$'; then
        DEVNODE="/dev/${dev}1"
    fi

    if [ -b "$DEVNODE" ]; then
        echo "[INIT] Tentando montar $DEVNODE..."

        mount -t auto "$DEVNODE" /mnt 2>/dev/null
        if [ $? -eq 0 ]; then
            if [ -f /mnt/init.sh ]; then
                echo "[INIT] init.sh encontrado em $DEVNODE! Executando..."
                chmod +x /mnt/init.sh
                setsid /mnt/init.sh
                FOUND="yes"
                break
            fi            
        fi
    fi
done

echo "[INIT] Execução de init.sh finalizada. Abrindo shell."
exec /bin/sh
EOF

chmod +x init

ls -lh

rm linuxrc

mkdir -p {bin,sbin,etc,proc,sys,usr/bin,usr/sbin,dev,tmp,var,mnt}

cd dev

mknod -m 622 console c 5 1
mknod -m 666 null c 1 3

cd ..

find . -print0 | cpio --null -ov --format=newc | gzip -9 > ../boot-partition/initramfs.cpio.gz

cd ..


#####################################################
### Criar ISO
#####################################################


cd src/linux
make isoimage FDINITRD=../../boot-partition/initramfs.cpio.gz FDARGS="initrd=/initramfs.cpio.gz"
cd ../..

qemu-system-x86_64 -cdrom src/linux/arch/x86/boot/image.iso -m 512



#####################################################
### init.sh em iso
#####################################################

cat <<EOF > init.sh
#!/bin/sh
echo "[INITCDROM] init.sh do CD-ROM foi executado."
EOF

chmod +x init.sh

xorriso -indev src/linux/arch/x86/boot/image.iso -outdev image.iso -map init.sh /init.sh

qemu-system-x86_64 -cdrom image.iso -m 512






